# Generated by Django 6.1.1 on 2026-10-02 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='image',
            field=models.ImageField(default='employee_images/default.png', upload_to='employee_images'),
        ),
    ]
