# Generated by Django 6.1.1 on 2026-10-02 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_alter_employee_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='image',
            field=models.ImageField(default='default.png', upload_to='employee_images'),
        ),
    ]
